apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Ensures PV is not deleted when PVC is removed
  storageClassName: manual
  hostPath:
    path: "/var/lib/rancher/k3s/storage/neo4j-pv"  # Set a persistent directory on the host
  claimRef:
    namespace: default
    name: neo4j-pvc
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual