apiVersion: v1
kind: PersistentVolume
metadata:
  name: qdrant-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Ensures PV is not deleted when PVC is removed
  hostPath:
    path: "/var/lib/rancher/k3s/storage/qdrant-pv"  # Set a persistent directory on the host
  storageClassName: manual
  claimRef:
    namespace: default
    name: qdrant-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual